### ISSUE TITLE
Need auto sort aliases

### ISSUE THREAD

**Issue by tonight-halfmoon** [elixir-editors/emacs-elixir#450]
Running mix credo on a project with option `--strict` may complain about unsorted aliases. For example:

`[R] ↘ The alias 'Xyz' is not alphabetically
┃       ordered among its group.`

Currently, running elixir-format won't sort the aliases alphabetically.

It would be so great to have this feature -- to alphabetically sort aliases in an elixir module (`ex` / `exs` files).

**Comment by victorolinasc** [comment]
This functionality does not belong (usually) to a major mode definition. This is better suited to language servers and/or specialized packages (like a credo package here).

There are, currently, plugins for the Elixir formatter. Styler from Adobe does exactly what you want and other things automatically. This is good because it is independent from Emacs and everybody can use it.
