### ISSUE TITLE
ExUnit functions highlighting issues. 

### ISSUE THREAD

**Issue by konstantinzolotarev** [elixir-editors/emacs-elixir#462]
I'm pretty new to Emacs and might be will write something not very clear. Sorry for that.

Some ExUnit keywords are displaying incorrectly (at least for me) 

- `describe` - does not have any color and acts just like normal text (should be same as `test` keyword)
- `test` - behaves as variable, it differs from `def`, `do`, `defmodule` might be it should be same ?
- `assert`, `refute`, `assert_raise` and other assertion functions behaves as Modules. Should be like other functions (or may be same as `@spec`, `@doc` ?

![Screenshot 2020-09-23 at 16 01 49](https://user-images.githubusercontent.com/286431/94015880-1b2c8880-fdb6-11ea-9ae1-7131328036bf.png)

**Comment by konstantinzolotarev** [comment]
BTW I'm happy to help if you will point me in direction on how could it be achieved =)

**Comment by jsmestad** [comment]
So this could be your emacs theme not making use of all the built-in font-lock options in Emacs. 

Where you need to add these if you want to propose them as an addition is inside [this block of code](https://github.com/elixir-editors/emacs-elixir/blob/master/elixir-mode.el#L94-L167).

What you may find is that describe is not a keyword per-se but a macro which is why it is not currently listed in the font-lock.

LMK if you need any more guidance on this one

**Comment by konstantinzolotarev** [comment]
@jsmestad Thank you very much. Will try to make required updates locally.
